{% set version = "1.9.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cvxr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/CVXR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/CVXR/CVXR_{{ version }}.tar.gz
  sha256: e1502049c09a0eee9b5dde260763de84e9bb5faa6780ad8d891fb03f9187bc11

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-clarabel >=0.11            # [build_platform != target_platform]
    - r-cli >=3.6                  # [build_platform != target_platform]
    - r-gmp >=0.7                  # [build_platform != target_platform]
    - r-highs >=1.14               # [build_platform != target_platform]
    - r-matrix >=1.7               # [build_platform != target_platform]
    - r-osqp >=1.0                 # [build_platform != target_platform]
    - r-rcpp >=1.1                 # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-s7 >=0.2                   # [build_platform != target_platform]
    - r-scs >=3.2                  # [build_platform != target_platform]
    - r-slam >=0.1                 # [build_platform != target_platform]
  host:
    - r-base
    - r-clarabel >=0.11
    - r-cli >=3.6
    - r-gmp >=0.7
    - r-highs >=1.14
    - r-matrix >=1.7
    - r-osqp >=1.0
    - r-rcpp >=1.1
    - r-rcppeigen
    - r-s7 >=0.2
    - r-scs >=3.2
    - r-slam >=0.1
  run:
    - r-base
    - r-clarabel >=0.11
    - r-cli >=3.6
    - r-gmp >=0.7
    - r-highs >=1.14
    - r-matrix >=1.7
    - r-osqp >=1.0
    - r-rcpp >=1.1
    - r-s7 >=0.2
    - r-scs >=3.2
    - r-slam >=0.1

test:
  commands:
    - $R -e "library('CVXR')"           # [not win]
    - "\"%R%\" -e \"library('CVXR')\""  # [win]

about:
  home: https://cvxr.rbind.io, https://www.cvxgrp.org/CVXR/
  dev_url: https://github.com/cvxgrp/CVXR
  license: Apache-2.0
  summary: An object-oriented modeling language for disciplined convex programming (DCP) as described in Fu, Narasimhan, and Boyd (2020, <doi:10.18637/jss.v094.i14>). It allows the user to formulate convex optimization problems in a natural way following mathematical convention and DCP rules. The system analyzes the 
    problem, verifies its convexity, converts it into a canonical form, and hands it off to an appropriate solver to obtain the solution. Interfaces to solvers on CRAN and elsewhere are provided, both commercial and open source.
  license_file:
    - APACHE-2.0.txt
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
